# Generated by Django 4.0.4 on 2022-06-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
