# Generated by Django 4.0.4 on 2022-06-23 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_item_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desciption',
            new_name='description',
        ),
    ]
