# Generated by Django 4.0.4 on 2022-06-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='images/noimage.jpg', upload_to='images'),
        ),
    ]
